export const nicknames = [
	'МaJLeHbkiu_MaFi0Ze',
	'IIo3uTuB4uK',
	'MaJIeHkuu_Ho_OnacHekuu',
	'McTuTeJIb',
	'3JlOu_XJlE6yWEK',
	'TBo9 cMepTb',
	'CuCe4Ka',
	'6a6ka B Hau`KoBCKuX KeDaX:D',
	'MaJIeHbkuu Prince',
	'JIuMoH4uk',
	'6y6JIuk',
	'TaTaPuH',
	'cMepTHuk',
	'MoJLoDoY',
	'CTepBo4ka',
	'Do6pbIu',
	'Cyxaruk',
	'ApXuTekToR',
	'NaGiB4Uk',
	'PoZiTiV4iK :3',
	'y6uBaH keHo6u',
	'T4WERKA',
	'ApAsNыЙ_GoPnIK',
	'Ma[L]oU',
	'MoJIoDou',
	'XaMeJleoH',
	'MaMKa_DoMa',
	'KopoJlb',
	'4ebyrek',
	'DeByшKa_TyT_Iгaet',
	'Mandarin4ik',
	'KARASIK',
	'4ebure4ek',
	'KaJIu6pu',
	'KoT_БоPuS',
	'MoToRoLa',
	'nu3gokaBbIp9lJIka',
	'kocou_c_kocou',
	'ХeT_SHОТ_ОТ BABKI',
	'Ru$$K0e_M9sO',
	'ПрИвЕт_В_ПрИцЕлЕ_AwP',
	'RaSp1zDяЙ',
	'oXoTHUK_3A_HACKAMU',
	'ДеДуЛя_ИЗ_FBI',
	'MaJIeHbkuu` SnipeR',
	'6oJlьHoй',
	'✘ацкер',
	'4ebyrek',
	'SHKOLNIK',
	'KyIIиdoN4иК-0-0-',
	'4uD@4oK',
	'ByJlo4ka',
	'Mexanik',
	'Golovore[z]',
	'4ekHyTbIuS',
	'3JlOU_LLIKOJliK',
	'Po4ka',
	'Uzbek',
	'βолченоk',
	'TpoJIb',
]
